#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Freebird Collab relay - single-file build (generated by relay/build_standalone.py, do not edit)
# Speaks raw TCP + WebSocket on one port. Listens on $PORT (default 7788).
import os, sys
# ======== protocol.py ========
# SPDX-License-Identifier: GPL-2.0-or-later
"""
Wire protocol for Freebird Collaboration Layer.

Framing : 4-byte big-endian length + UTF-8 JSON payload.
Routing : every message carries "t" (type). The hub (relay or direct host)
          forwards a message to every other peer in the room, or only to
          msg["to"] when present. Fields "from" and "room" are stamped by hub.

Message types (client -> hub -> peers):
  hello           {name, role: host|guest, room, color}     first message, hub replies welcome
  welcome         {uid, room, peers:[{uid,name,role,color}], host_uid}
  peer_join       {uid, name, role, color}
  peer_leave      {uid}
  error           {msg}
  scene           {to, blend_b64, filename}                  host -> new guest, one-shot
  presence        {vr, head:[x,y,z,qw,qx,qy,qz]|null, hands:{L:[..7 + ray(0/1)], R:[..]},
                   tool, sel:[names], mode}                  ~20 Hz
  xform           {objs:{name:[16 floats]}}                  only for changed objects
  obj_add         {name, type, mesh:{v:[[x,y,z]..], f:[[i..]..]}|null, m:[16]}
  obj_del         {names:[..]}
  save            {}                                         guest -> host: please save master
  ping / pong     {}
"""

import json
import struct

HEADER = struct.Struct(">I")
MAX_FRAME = 256 * 1024 * 1024  # 256 MB (scene snapshots)
PROTOCOL_VERSION = 1


def encode(msg: dict) -> bytes:
    body = json.dumps(msg, separators=(",", ":"), ensure_ascii=False).encode("utf-8")
    if len(body) > MAX_FRAME:
        raise ValueError("frame too large")
    return HEADER.pack(len(body)) + body


class Decoder:
    """Incremental frame decoder. feed(bytes) -> list[dict]."""

    def __init__(self):
        self._buf = bytearray()

    def feed(self, data: bytes):
        self._buf.extend(data)
        out = []
        while True:
            if len(self._buf) < HEADER.size:
                break
            (n,) = HEADER.unpack_from(self._buf, 0)
            if n > MAX_FRAME:
                raise ValueError("frame too large")
            if len(self._buf) < HEADER.size + n:
                break
            body = bytes(self._buf[HEADER.size : HEADER.size + n])
            del self._buf[: HEADER.size + n]
            out.append(json.loads(body.decode("utf-8")))
        return out


def make(t: str, **fields) -> dict:
    fields["t"] = t
    return fields

# ======== ws.py ========
# SPDX-License-Identifier: GPL-2.0-or-later
"""
Minimal WebSocket (RFC 6455) over a plain socket, stdlib only.
Enough for the relay: text frames carrying one JSON message each,
ping/pong/close handling, client-side masking, 64-bit lengths.

Why: free hosting (Hugging Face Spaces, Render, Cloudflare tunnels...) only
forwards HTTP/WebSocket, not raw TCP. The hub speaks both on one port.
"""

import base64
import hashlib
import os
import struct
from urllib.parse import urlparse

GUID = "258EAFA5-E914-47DA-95CA-C5AB0DC85B11"
OP_CONT, OP_TEXT, OP_BIN, OP_CLOSE, OP_PING, OP_PONG = 0x0, 0x1, 0x2, 0x8, 0x9, 0xA


def _recv_exact(sock, n):
    buf = bytearray()
    while len(buf) < n:
        chunk = sock.recv(min(n - len(buf), 1 << 20))
        if not chunk:
            raise ConnectionError("socket closed")
        buf.extend(chunk)
    return bytes(buf)


def _read_http_head(sock, first=b""):
    data = bytearray(first)
    while b"\r\n\r\n" not in data:
        chunk = sock.recv(4096)
        if not chunk:
            raise ConnectionError("socket closed during HTTP head")
        data.extend(chunk)
        if len(data) > 65536:
            raise ValueError("HTTP head too large")
    head, _, rest = bytes(data).partition(b"\r\n\r\n")
    return head.decode("latin-1"), rest


def _parse_headers(head):
    lines = head.split("\r\n")
    start = lines[0]
    headers = {}
    for ln in lines[1:]:
        k, _, v = ln.partition(":")
        headers[k.strip().lower()] = v.strip()
    return start, headers


# ----------------------------------------------------------------------
# server side
# ----------------------------------------------------------------------
def server_handshake(sock, first_bytes=b""):
    """
    Call after peeking that the connection starts with an HTTP request.
    Returns True when upgraded to WebSocket, False when it was a plain HTTP
    request (a 200 health response was sent; caller should close).
    """
    head, _rest = _read_http_head(sock, first_bytes)
    start, h = _parse_headers(head)
    if h.get("upgrade", "").lower() != "websocket" or "sec-websocket-key" not in h:
        body = b"freebird-collab relay ok\n"
        sock.sendall(
            b"HTTP/1.1 200 OK\r\nContent-Type: text/plain\r\nContent-Length: "
            + str(len(body)).encode()
            + b"\r\nConnection: close\r\n\r\n"
            + body
        )
        return False
    accept = base64.b64encode(hashlib.sha1((h["sec-websocket-key"] + GUID).encode()).digest()).decode()
    sock.sendall(
        (
            "HTTP/1.1 101 Switching Protocols\r\n"
            "Upgrade: websocket\r\n"
            "Connection: Upgrade\r\n"
            f"Sec-WebSocket-Accept: {accept}\r\n\r\n"
        ).encode()
    )
    return True


# ----------------------------------------------------------------------
# client side
# ----------------------------------------------------------------------
def parse_url(url: str):
    """'wss://host/path' | 'ws://host:port' | 'tcp://host:port' | 'host:port' -> (scheme, host, port, path)"""
    url = url.strip()
    if "://" not in url:
        url = "tcp://" + url
    u = urlparse(url)
    scheme = u.scheme.lower()
    if scheme not in ("ws", "wss", "tcp"):
        raise ValueError(f"unsupported scheme: {scheme}")
    port = u.port or {"ws": 80, "wss": 443, "tcp": 7788}[scheme]
    return scheme, u.hostname, port, (u.path or "/")


def client_handshake(sock, host, path="/", port=None):
    key = base64.b64encode(os.urandom(16)).decode()
    hosthdr = host if port in (None, 80, 443) else f"{host}:{port}"
    sock.sendall(
        (
            f"GET {path} HTTP/1.1\r\n"
            f"Host: {hosthdr}\r\n"
            "Upgrade: websocket\r\n"
            "Connection: Upgrade\r\n"
            f"Sec-WebSocket-Key: {key}\r\n"
            "Sec-WebSocket-Version: 13\r\n"
            "User-Agent: freebird-collab/0.2\r\n\r\n"
        ).encode()
    )
    head, rest = _read_http_head(sock)
    start, h = _parse_headers(head)
    if " 101 " not in start:
        raise ConnectionError(f"websocket handshake refused: {start}")
    expect = base64.b64encode(hashlib.sha1((key + GUID).encode()).digest()).decode()
    if h.get("sec-websocket-accept") != expect:
        raise ConnectionError("bad Sec-WebSocket-Accept")
    return rest  # leftover bytes (start of first frame, if any)


# ----------------------------------------------------------------------
# frames
# ----------------------------------------------------------------------
def build_frame(payload: bytes, opcode=OP_TEXT, mask=False) -> bytes:
    n = len(payload)
    head = bytearray([0x80 | opcode])
    mbit = 0x80 if mask else 0
    if n < 126:
        head.append(mbit | n)
    elif n < 65536:
        head.append(mbit | 126)
        head += struct.pack(">H", n)
    else:
        head.append(mbit | 127)
        head += struct.pack(">Q", n)
    if mask:
        key = os.urandom(4)
        head += key
        payload = bytes(b ^ key[i % 4] for i, b in enumerate(payload)) if n < 4096 else _mask_fast(payload, key)
    return bytes(head) + payload


def _mask_fast(payload: bytes, key: bytes) -> bytes:
    # xor with the 4-byte key using int arithmetic on big chunks
    n = len(payload)
    full = n - (n % 4)
    k = int.from_bytes(key * (full // 4), "big") if full else 0
    out = (int.from_bytes(payload[:full], "big") ^ k).to_bytes(full, "big") if full else b""
    tail = bytes(b ^ key[i % 4] for i, b in enumerate(payload[full:], start=full))
    return out + tail


class FrameReader:
    """Reads complete messages from a socket. Yields (opcode, payload)."""

    def __init__(self, sock, leftover=b""):
        self.sock = sock
        self._buf = bytearray(leftover)
        self._msg = bytearray()
        self._msg_op = None

    def _need(self, n):
        while len(self._buf) < n:
            chunk = self.sock.recv(1 << 20)
            if not chunk:
                raise ConnectionError("socket closed")
            self._buf.extend(chunk)
        out = bytes(self._buf[:n])
        del self._buf[:n]
        return out

    def read_message(self):
        while True:
            b0, b1 = self._need(2)
            fin, op = b0 & 0x80, b0 & 0x0F
            masked, n = b1 & 0x80, b1 & 0x7F
            if n == 126:
                (n,) = struct.unpack(">H", self._need(2))
            elif n == 127:
                (n,) = struct.unpack(">Q", self._need(8))
            key = self._need(4) if masked else None
            payload = self._need(n)
            if key:
                payload = _mask_fast(payload, key)
            if op in (OP_PING, OP_PONG, OP_CLOSE):
                return op, payload
            if op != OP_CONT:
                self._msg_op = op
                self._msg = bytearray()
            self._msg.extend(payload)
            if fin:
                out = bytes(self._msg)
                self._msg = bytearray()
                return self._msg_op, out

# ======== hub.py ========
# SPDX-License-Identifier: GPL-2.0-or-later
"""
Room hub: accepts TCP clients, groups them into rooms, forwards frames.

Used in two ways:
  * standalone relay server  (relay/collab_relay.py wraps this)      -> Room-code UX
  * embedded in the HOST's Blender (direct mode, host = hub)         -> IP:port debug UX

Pure stdlib, no bpy dependency, so it is unit-testable outside Blender.
"""

import secrets
import socket
import threading
import time

import sys as _s; wsmod = _s.modules[__name__]


ROOM_ALPHABET = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789"  # no 0/O/1/I


def new_room_code(n=6):
    return "".join(secrets.choice(ROOM_ALPHABET) for _ in range(n))


class _Client:
    def __init__(self, sock, addr, uid):
        self.sock = sock
        self.addr = addr
        self.uid = uid
        self.name = "?"
        self.role = "guest"
        self.color = [1, 1, 1]
        self.room = None
        self.lock = threading.Lock()
        self.alive = True
        self.ws = False  # True after a WebSocket upgrade

    def send(self, msg):
        try:
            if self.ws:
                data = wsmod.build_frame(encode(msg)[4:], wsmod.OP_TEXT, mask=False)
            else:
                data = encode(msg)
            with self.lock:
                self.sock.sendall(data)
        except OSError:
            self.alive = False


class Hub:
    def __init__(self, host="0.0.0.0", port=0, fixed_room=None, log=print):
        """
        fixed_room: when set (direct mode), the first host hello gets this code
                    instead of a random one, so guests can join with any code.
        """
        self.host = host
        self.port = port
        self.fixed_room = fixed_room
        self.log = log
        self.rooms = {}  # code -> {uid: _Client}
        self.clients = {}
        self._lock = threading.RLock()
        self._srv = None
        self._thread = None
        self._uid_counter = 0
        self.running = False

    # ---- lifecycle ---------------------------------------------------
    def start(self):
        self._srv = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self._srv.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        self._srv.bind((self.host, self.port))
        self._srv.listen(16)
        self.port = self._srv.getsockname()[1]
        self.running = True
        self._thread = threading.Thread(target=self._accept_loop, name="collab-hub", daemon=True)
        self._thread.start()
        self.log(f"[hub] listening on {self.host}:{self.port}")
        return self.port

    def stop(self):
        self.running = False
        try:
            self._srv.close()
        except OSError:
            pass
        with self._lock:
            for c in list(self.clients.values()):
                try:
                    c.sock.close()
                except OSError:
                    pass
            self.clients.clear()
            self.rooms.clear()

    # ---- networking --------------------------------------------------
    def _accept_loop(self):
        while self.running:
            try:
                sock, addr = self._srv.accept()
            except OSError:
                break
            sock.setsockopt(socket.IPPROTO_TCP, socket.TCP_NODELAY, 1)
            with self._lock:
                self._uid_counter += 1
                uid = f"u{self._uid_counter}"
                c = _Client(sock, addr, uid)
                self.clients[uid] = c
            threading.Thread(target=self._client_loop, args=(c,), daemon=True).start()

    def _client_loop(self, c: _Client):
        try:
            # one port, two dialects: raw length-prefixed TCP, or HTTP -> WebSocket
            first = c.sock.recv(4, socket.MSG_PEEK)
            if not first:
                return
            if first.startswith(b"GET ") or first.startswith(b"HEAD") or first.startswith(b"POST"):
                if not wsmod.server_handshake(c.sock):
                    return  # plain HTTP health check, already answered
                c.ws = True
                self._ws_loop(c)
            else:
                self._tcp_loop(c)
        except (OSError, ValueError, ConnectionError):
            pass
        finally:
            self._drop(c)

    def _tcp_loop(self, c: _Client):
        dec = Decoder()
        while self.running and c.alive:
            data = c.sock.recv(65536)
            if not data:
                break
            for msg in dec.feed(data):
                self._handle(c, msg)

    def _ws_loop(self, c: _Client):
        import json

        reader = wsmod.FrameReader(c.sock)
        while self.running and c.alive:
            op, payload = reader.read_message()
            if op == wsmod.OP_CLOSE:
                break
            if op == wsmod.OP_PING:
                with c.lock:
                    c.sock.sendall(wsmod.build_frame(payload, wsmod.OP_PONG))
                continue
            if op in (wsmod.OP_TEXT, wsmod.OP_BIN):
                self._handle(c, json.loads(payload.decode("utf-8")))

    # ---- room logic --------------------------------------------------
    def _handle(self, c: _Client, msg: dict):
        t = msg.get("t")
        if t == "hello":
            self._hello(c, msg)
            return
        if t == "ping":
            c.send(make("pong"))
            return
        if c.room is None:
            c.send(make("error", msg="not in a room"))
            return
        msg["from"] = c.uid
        to = msg.get("to")
        with self._lock:
            peers = list(self.rooms.get(c.room, {}).values())
        for p in peers:
            if p is c:
                continue
            if to and p.uid != to:
                continue
            p.send(msg)

    def _hello(self, c: _Client, msg: dict):
        c.name = str(msg.get("name", "user"))[:32]
        c.role = "host" if msg.get("role") == "host" else "guest"
        c.color = msg.get("color", [1, 1, 1])
        code = (msg.get("room") or "").strip().upper()
        with self._lock:
            if c.role == "host":
                code = self.fixed_room or code or new_room_code()
                if code in self.rooms and any(p.role == "host" for p in self.rooms[code].values()):
                    c.send(make("error", msg=f"room {code} already has a host"))
                    return
                self.rooms.setdefault(code, {})
            else:
                if self.fixed_room:
                    code = self.fixed_room
                if code not in self.rooms:
                    c.send(make("error", msg=f"room {code} not found"))
                    return
            room = self.rooms[code]
            room[c.uid] = c
            c.room = code
            peers = [
                {"uid": p.uid, "name": p.name, "role": p.role, "color": p.color} for p in room.values() if p is not c
            ]
            host_uid = next((p.uid for p in room.values() if p.role == "host"), None)
        c.send(make("welcome", uid=c.uid, room=code, peers=peers, host_uid=host_uid, version=1))
        self._broadcast(c, make("peer_join", uid=c.uid, name=c.name, role=c.role, color=c.color))
        self.log(f"[hub] {c.name}({c.role}) joined room {code}")

    def _broadcast(self, sender: _Client, msg: dict):
        with self._lock:
            peers = [p for p in self.rooms.get(sender.room, {}).values() if p is not sender]
        for p in peers:
            p.send(msg)

    def _drop(self, c: _Client):
        c.alive = False
        with self._lock:
            self.clients.pop(c.uid, None)
            room = self.rooms.get(c.room)
            if room:
                room.pop(c.uid, None)
                if not room:
                    del self.rooms[c.room]
        try:
            c.sock.close()
        except OSError:
            pass
        if c.room:
            self._broadcast(c, make("peer_leave", uid=c.uid))
            self.log(f"[hub] {c.name} left room {c.room}")


def serve_forever(host="0.0.0.0", port=7788):
    hub = Hub(host, port)
    hub.start()
    try:
        while True:
            time.sleep(1)
    except KeyboardInterrupt:
        hub.stop()


if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("PORT", "7788"))
    print(f"Freebird Collab relay on port {port} (tcp + websocket)", flush=True)
    serve_forever("0.0.0.0", port)
