#!/usr/bin/env python3
"""Inline protocol.py + ws.py + hub.py into one dependency-free file: relay/standalone/app.py (for Render / any Docker host)
(run after editing those modules)."""
import os, re
root = os.path.join(os.path.dirname(os.path.abspath(__file__)), "..")
parts = []
for name in ("protocol", "ws", "hub"):
    src = open(os.path.join(root, "freebird_collab", f"{name}.py"), encoding="utf-8").read()
    src = re.sub(r"^from \.(\w+) import .*$", "", src, flags=re.M)   # in-package imports become globals
    src = re.sub(r"^from \. import ws as wsmod$", "import sys as _s; wsmod = _s.modules[__name__]", src, flags=re.M)
    parts.append(f"# ======== {name}.py ========\n{src}")
out = '''#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
# Freebird Collab relay - single-file build (generated by relay/build_standalone.py, do not edit)
# Speaks raw TCP + WebSocket on one port. Listens on $PORT (default 7788).
import os, sys
''' + "\n".join(parts) + '''

if __name__ == "__main__":
    port = int(sys.argv[1]) if len(sys.argv) > 1 else int(os.environ.get("PORT", "7788"))
    print(f"Freebird Collab relay on port {port} (tcp + websocket)", flush=True)
    serve_forever("0.0.0.0", port)
'''
open(os.path.join(root, "relay", "standalone", "app.py"), "w", encoding="utf-8").write(out)
print("wrote relay/standalone/app.py")
